# Generated by Django 3.2.6 on 2021-08-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_auto_20210819_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_account', models.CharField(max_length=20)),
                ('from_account', models.CharField(max_length=20)),
                ('transact_time', models.CharField(max_length=500)),
            ],
        ),
    ]
