# Generated by Django 3.2.6 on 2021-08-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
